// Copies the Broadcast typefaces into web/lib/fonts/ and writes fonts.css
// (docs/plan.md section 2): Archivo for UI and headings, IBM Plex Mono for
// every measurement. Source: the pinned @fontsource devDependencies, latin
// subset only (covers German and the other western European languages).
// Both families are SIL OFL 1.1; the licence ships next to the files.
// Self-hosted so the app never requests Google Fonts at runtime.
//   pnpm run vendor:fonts      (never hand-edit web/lib/fonts/)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const FACES = [
  { pkg: 'archivo', family: 'Archivo', weights: [400, 500, 600, 700] },
  { pkg: 'ibm-plex-mono', family: 'IBM Plex Mono', weights: [400, 500] },
];

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'web/lib/fonts');
fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });

let css = '/* Generated by scripts/vendor-fonts.mjs - do not edit. SIL OFL 1.1, see OFL.txt. */\n';
for (const { pkg, family, weights } of FACES) {
  const dir = path.join(root, 'node_modules/@fontsource', pkg);
  for (const w of weights) {
    const file = `${pkg}-latin-${w}-normal.woff2`;
    fs.copyFileSync(path.join(dir, 'files', file), path.join(out, file));
    css += `@font-face {\n  font-family: '${family}';\n  font-style: normal;\n  font-weight: ${w};\n  font-display: swap;\n` +
      `  src: url('./${file}') format('woff2');\n}\n`;
  }
}
fs.writeFileSync(path.join(out, 'fonts.css'), css);
// Both licences: same OFL text, different copyright holders.
fs.writeFileSync(path.join(out, 'OFL.txt'), FACES.map(({ pkg, family }) =>
  `===== ${family} =====\n\n${fs.readFileSync(path.join(root, 'node_modules/@fontsource', pkg, 'LICENSE'), 'utf8')}`).join('\n\n'));
console.log(`vendor-fonts: ${FACES.map((f) => `${f.family} ${f.weights.join('/')}`).join(', ')} -> web/lib/fonts/`);
